# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59d15d773e3e4671e9f2add9ab1226e66ba24ba93cac7e0c949678ddc10e23f5791e255e3e813f5deca444553b282f0acbd15cdd1a9f89d0bc12283cdc745211

test:
  secret_key_base: 19f1190c9983284283bd06bec846d3ebece8734d96ebc3e856b04fdee263ede240d65c6c3f46fad88278af3eb349f52cae6a8c9ea8e66cd21ab4f2e5cfb44c28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
